### ISSUE TITLE
Text Summarization

### ISSUE THREAD

**Issue by sarthakpan** [hotpads/ERNIE-for-the-Rest-of-Us#2]
How to use this package for text summarization?
I even cannot figure out how to get back text from tensor generated from:
outputs = ernie_model(record.as_tuple())
outputs = ernie4us.Ernie2Output(sequence_features=outputs[0], classification_features=outputs[1])

What I want is abstract summary for a given text file.

**Comment by winston-zillow** [comment]
ERNIE provides the basic pre-trained language model, so one has to adopt it for various applications. As ERNIE has essentially the same architecture as BERT, one can follow similar approach like [this](https://deeplearninganalytics.org/text-summarization/) to fine-tune it for text summarization.
